version: '3'

services:
  user-service:
    build: ./user
    ports:
      - "5000:5000"
    networks:
      - microservices-network

  flight-service:
    build: ./flight
    ports:
      - "5001:5001"
    networks:
      - microservices-network

  booking-service:
    build: ./booking
    ports:
      - "5002:5002"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
